### ISSUE TITLE
Force fullscreen

### ISSUE THREAD

**Issue by MaartenSomay** [soshikimoe/soshiki-ios#22]
Add force fullscreen option

**Comment by bachig26** [comment]
![IMG_6806](https://user-images.githubusercontent.com/96393348/222304871-745dc12f-7b44-4ca2-99c8-1ffbbd8c9f14.PNG)

**Comment by phiefferj24** [comment]
Forcing fullscreen is only possible with private API through AVKit which would make it impossible to publish the app later on.
