### ISSUE TITLE
Add Threshold when ep is completed

### ISSUE THREAD

**Issue by MaartenSomay** [soshikimoe/soshiki-ios#29]
So it shows the next ep at ‘continue watching’

‘Start Watching Ep…’ maybe?

**Comment by tyrohellion** [comment]
To build onto this, the auto tracking should wait till this threshold is achieved before updating trackers. Right now it updates as soon as a user starts an episode (at least that's how it was for me)

**Comment by phiefferj24** [comment]
Will be in 0.3

> To build onto this, the auto tracking should wait till this threshold is achieved before updating trackers. Right now it updates as soon as a user starts an episode (at least that's how it was for me)

This is also done in 0.3
